version: '2'

services:
  database:
    image: exhuma/powonline-db:latest
    restart: always
    volumes:
      - powonline-db-data:/var/lib/postgresql
    networks:
      - nginxproxy_default

  api:
    image: exhuma/powonline-api:latest
    restart: always
    networks:
      - nginxproxy_default
    volumes:
      - powonline-api-config:/etc/mamerwiselen/powonline
    env_file: api.env

  frontend:
    image: exhuma/powonline-frontend:latest
    restart: always
    networks:
      - nginxproxy_default
    env_file: frontend.env

networks:
  nginxproxy_default:
    external: true

volumes:
    powonline-api-config:
    powonline-db-data:
