<template>
  <v-tabs v-model="selectedLanguage" grow slider-color="yellow">
    <v-tab href="#en" ripple>en</v-tab>
    <v-tab href="#fr" ripple>fr</v-tab>
    <v-tab href="#de" ripple>de</v-tab>
    <v-tab-item value="en">
    <v-card flat>
        <v-card-text class="text-xs-left">
        <h1>Privacy Policy</h1>

        <p>Effective date: May 09, 2019</p>

        <p>Lost Tracker ("us", "we", or "our") operates the https://tracker.lost.lu website (hereinafter referred to as the "Service").</p>

        <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

        <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://tracker.lost.lu</p>

        <h2>Definitions</h2>
        <ul>
            <li>
                <p><strong>Service</strong></p>
                        <p>Service is the https://tracker.lost.lu website operated by Lost Tracker</p>
                    </li>
            <li>
                <p><strong>Personal Data</strong></p>
                <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            </li>
            <li>
                <p><strong>Usage Data</strong></p>
                <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li>
                <p><strong>Cookies</strong></p>
                <p>Cookies are small files stored on your device (computer or mobile device).</p>
            </li>
                <li>
                <p><strong>Data Controller</strong></p>
                <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
            </li>
            <li>
                <p><strong>Data Processors (or Service Providers)</strong></p>
                <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                <p>We may use the services of various Service Providers in order to process your data more effectively.</p>
            </li>
            <li>
                <p><strong>Data Subject (or User)</strong></p>
                <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
            </li>
            </ul>

        <h2>Information Collection and Use</h2>
        <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

        <h3>Types of Data Collected</h3>

        <h4>Personal Data</h4>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

        <ul>
            <li>Email address</li>        <li>Phone number</li>        <li>Cookies and Usage Data</li>
        </ul>

        <h4>Usage Data</h4>

        <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

        <h4>Tracking & Cookies Data</h4>
        <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
        <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
        <p>Examples of Cookies we use:</p>
        <ul>
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
            </ul>

        <h2>Use of Data</h2>
        <p>Lost Tracker uses the collected data for various purposes:</p>
        <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            </ul>

        <h2>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h2>
        <p>If you are from the European Economic Area (EEA), Lost Tracker legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
        <p>Lost Tracker may process your Personal Data because:</p>
        <ul>
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
                <li>To comply with the law</li>
        </ul>

        <h2>Retention of Data</h2>
        <p>Lost Tracker will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
        <p>Lost Tracker will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

        <h2>Transfer of Data</h2>
        <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p>If you are located outside Luxembourg and choose to provide information to us, please note that we transfer the data, including Personal Data, to Luxembourg and process it there.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p>Lost Tracker will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

        <h2>Disclosure of Data</h2>

        <h3>Legal Requirements</h3>
        <p>Lost Tracker may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Lost Tracker</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
        </ul>

        <h2>Security of Data</h2>
        <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h2>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
        <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Lost Tracker aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
        <p>If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
        <p>In certain circumstances, you have the following data protection rights:</p>
        <ul>
            <li>
                <p><strong>The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
            </li>
            <li>
                <p><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
            </li>
            <li>
                <p><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</p>
            </li>
            <li>
                <p><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</p>
            </li>
            <li>
                <p><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
            </li>
            <li>
                <p><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Lost Tracker relied on your consent to process your personal information.</p>
            </li>
        </ul>
        <p>Please note that we may ask you to verify your identity before responding to such requests.</p>

        <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

        <h2>Service Providers</h2>
        <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
        <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

        <h2>Links to Other Sites</h2>
        <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h2>Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 18 ("Children").</p>
        <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

        <h2>Changes to This Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us:</p>
        <ul>
                <li>By email: cheffen@lost.lu</li>
        </ul>
        </v-card-text>
    </v-card>
    </v-tab-item>
    <v-tab-item value="fr">
    <v-card flat>
        <v-card-text class="text-xs-left">
        <h1>Politique de Confidentialité</h1>

        <p>Date de prise d'effet: May 09, 2019</p>

        <p>Lost Tracker ("nous", "notre", "nos") exploite le site web https://tracker.lost.lu (ci-après désigné par le terme "Service").</p>

        <p>Cette page vous explique nos politiques en matière de collecte, d'utilisation et de communication des données à caractère personnel lorsque vous utilisez notre Service ainsi que les choix qui s'offrent à vous en ce qui concerne ces données.</p>

        <p>Nous utilisons vos données pour fournir et améliorer le Service. En utilisant le Service, vous consentez à la collecte et à l'utilisation d'informations conformément à la présente politique. Sauf définition contraire dans la présente Politique de Confidentialité, les termes utilisés dans la présente Politique de Confidentialité ont la même signification que dans nos Conditions Générales qui sont disponibles sur https://tracker.lost.lu</p>

        <h2>Définitions</h2>
        <ul>
            <li>
                <p><strong>Service</strong></p>
                        <p>Par Service on entend le site web https://tracker.lost.lu exploité par Lost Tracker</p>
                    </li>
            <li>
                <p><strong>Données à caractère personnel</strong></p>
                <p>Données à Caractère Personnel désigne des données concernant un individu vivant qui peut être identifié à partir de ces données (ou à partir de ces données et d'autres informations en notre possession ou susceptibles d'entrer en notre possession).</p>
            </li>
            <li>
                <p><strong>Données d'Utilisation</strong></p>
                <p>Les Données d'Utilisation sont recueillies automatiquement et sont générées soit par l'utilisation du Service, soit par l'infrastructure du Service proprement dite (par exemple, durée de consultation d'une page).</p>
            </li>
            <li>
                <p><strong>Cookies</strong></p>
                <p>Les cookies sont de petits fichiers enregistrés sur votre dispositif (ordinateur ou dispositif mobile).</p>
            </li>
                <li>
                <p><strong>Responsable du Traitement</strong></p>
                <p>Responsable du Traitement désigne la personne physique ou morale (seule, ou conjointement ou en commun avec d'autres personnes) qui détermine les finalités et les modalités selon lesquelles toutes les données personnelles sont traitées ou doivent l'être.</p>
                <p>Aux fins de la présente Politique de Confidentialité, nous sommes un Responsable du Traitement de vos données à caractère personnel.</p>
            </li>
            <li>
                <p><strong>Sous-Traitants (ou Prestataires de Services)</strong></p>
                <p>Le terme Sous-Traitant (ou Prestataire de Service) désigne toute personne physique ou morale qui traite les données au nom du Responsable du Traitement.</p>
                <p>Il se peut que nous fassions appel aux services de plusieurs Prestataires de Services afin de traiter vos données plus efficacement.</p>
            </li>
            <li>
                <p><strong>Personne Concernée (ou Utilisateur)</strong></p>
                <p>Par Personne Concernée, on entend toute personne vivante qui utilise notre Service et est le sujet de Données à Caractère Personnel. </p>
            </li>
            </ul>

        <h2>Collecte et utilisation des données</h2>
        <p>Nous recueillons plusieurs types de données à différentes fins en vue de vous fournir notre Service et de l'améliorer.</p>

        <h3>Types de données recueillies</h3>

        <h4>Données à Caractère Personnel</h4>
        <p>Lorsque vous utilisez notre Service, il est possible que nous vous demandions de nous fournir certaines données personnelles nominatives qui peuvent servir à vous contacter ou à vous identifier ("Données à Caractère Personnel"). Les données personnelles nominatives peuvent comprendre, mais de manière non limitative:</p>

        <ul>
            <li>Adresse e-mail</li>        <li>Numéro de téléphone</li>        <li>Cookies et Données d'Utilisation</li>
        </ul>

        <h4>Données d'Utilisation</h4>

        <p>Nous pouvons également recueillir des informations relatives au mode d'accès et d'utilisation du Service ("Données d'Utilisation"). Ces Données d'Utilisation peuvent comprendre des informations telles que l'adresse de protocole Internet (c.-à-d. l'adresse IP) de votre ordinateur, le type de navigateur, la version du navigateur, les pages de notre Service que vous consultez, la date et l'heure de votre visite, le temps passé sur ces pages, les identifiants uniques de dispositifs ainsi que d'autres données de diagnostic.</p>

        <h4>Suivi et données de cookies</h4>
        <p>Nous avons recours à des cookies et à d'autres technologies de suivi similaires pour effectuer un suivi des activités effectuées dans notre Service, et nous conservons certaines informations.</p>
        <p>Les cookies sont des fichiers à faible volume de données pouvant comporter un identifiant unique anonyme. Les cookies sont envoyés à votre navigateur depuis un site web et sont stockés sur votre dispositif. D'autres technologies de suivi telles que les pixels, les balises et les scripts sont également utilisées pour recueillir et suivre des informations et afin d'améliorer et d'analyser notre Service.</p>
        <p>Vous pouvez demander à votre navigateur de refuser tous les cookies ou de vous avertir lorsqu'un cookie est envoyé. Toutefois, si vous n'acceptez pas les cookies, il se peut que vous ne puissiez pas utiliser certains éléments de notre Service.</p>
        <p>Exemples de cookies que nous utilisons :</p>
        <ul>
            <li><strong>Cookies de Session.</strong> Nous utilisons des Cookies de Session pour faire fonctionner notre Service.</li>
            <li><strong>Cookies de Préférences.</strong> Nous utilisons des Cookies de Préférences pour mémoriser vos préférences et vos différents paramètres.</li>
            <li><strong>Cookies de Sécurité.</strong> Nous utilisons des Cookies de Sécurité pour des raisons de sécurité.</li>
            </ul>

        <h2>Utilisation des données</h2>
        <p>Lost Tracker utilise les données recueillies à des fins diverses:</p>
        <ul>
            <li>Pour fournir et assurer notre Service</li>
            <li>Pour vous faire part des changements apportés à notre Service</li>
            <li>Pour vous permettre d'utiliser les fonctions interactives de notre Service quand vous le souhaitez</li>
            <li>Pour assurer l'assistance client</li>
            <li>Pour recueillir des données précieuses ou d'analyses qui nous permettront d'améliorer notre Service</li>
            <li>Pour contrôler l'utilisation de notre Service</li>
            <li>Pour détecter, prévenir et régler les problèmes techniques</li>
            </ul>

        <h2>Fondement juridique du traitement des données à caractère personnel en vertu du Règlement Général relatif à la Protection des Données (RGPD)</h2>
        <p>Si vous résidez dans l'Espace économique européen (EEE), le fondement juridique de Lost Tracker en ce qui concerne la collecte et l'utilisation des données personnelles décrites dans la présente Politique de Confidentialité dépend des Données à Caractère Personnel que nous recueillons et du contexte précis dans lequel nous les recueillons.</p>
        <p>Lost Tracker peut traiter vos Données à Caractère Personnel:</p>
        <ul>
            <li>Parce que nous avons besoin d'exécuter un contrat passé avec vous</li>
            <li>Parce que vous nous avez autorisés à le faire</li>
            <li>Parce que nous avons un intérêt légitime à effectuer ce traitement et que vos droits ne priment pas sur cet intérêt légitime</li>
                <li>Pour respecter la loi</li>
        </ul>

        <h2>Conservation des données</h2>
        <p>Lost Tracker ne conservera vos Données à Caractère Personnel que tant que cela sera nécessaire aux fins stipulées dans la présente Politique de Confidentialité. Nous conserverons et utiliserons vos Données à Caractère Personnel dans la mesure où cela sera nécessaire pour que nous puissions nous acquitter de nos obligations légales (par exemple, pour respecter la législation en vigueur), résoudre des différends et appliquer nos accords et nos politiques.</p>
        <p>Lost Tracker conservera également les Données d'Utilisation à des fins d'analyses internes. Les Données d'Utilisation sont généralement conservées pour une période plus courte, sauf lorsque ces données sont utilisées pour renforcer la sécurité ou pour améliorer les fonctionnalités de notre Service, ou si nous sommes légalement tenus de conserver ces données plus longtemps.</p>

        <h2>Transfert des données</h2>
        <p>Les informations vous concernant, notamment vos Données à Caractère Personnel, peuvent être transférées de votre région, province, pays, ou autre division territoriale vers des ordinateurs – et stockées sur ces derniers – situés à un endroit où la législation relative à la protection des données diffère de celle du territoire où vous résidez.</p>
        <p>Si vous résidez hors de/du Luxembourg et que vous choisissez de nous communiquer des informations, sachez que nous transférons les données, y compris les Données à Caractère Personnel, vers le/la Luxembourg et que nous les y traitons.</p>
        <p>En acceptant la présente Politique de Confidentialité puis en soumettant ces informations, vous consentez à ce transfert.</p>
        <p>Lost Tracker prendra toutes les mesures raisonnablement nécessaires pour faire en sorte que vos données soient traitées de manière sécurisée et conformément à la présente Politique de Confidentialité et vos Données à Caractère Personnel ne seront transférées vers aucune organisation ni aucun pays à moins que des contrôles adéquats ne soient en place, notamment en ce qui concerne la sécurité de vos données et d'autres données personnelles.</p>

        <h2>Communication de données</h2>

        <h3>Exigences légales</h3>
        <p>Lost Tracker peut communiquer vos Données à Caractère Personnel si elle estime de bonne foi que cela est nécessaire pour:</p>
        <ul>
            <li>S'acquitter d'une obligation légale</li>
            <li>Protéger et défendre les droits ou les biens de Lost Tracker</li>
            <li>Prévenir d'éventuels actes répréhensibles ou enquêter sur de tels actes dans le cadre du Service </li>
            <li>Assurer la sécurité personnelle des utilisateurs du Service ou du public</li>
            <li>Se protéger contre la responsabilité civile</li>
        </ul>

        <h2>Sécurité des données</h2>
        <p>La sécurité de vos données nous tient à cœur. Toutefois, n'oubliez pas qu'aucune méthode de transmission de données par Internet ou méthode de stockage électronique n'est sûre à 100 %. Bien que nous nous efforcions d'utiliser des méthodes commercialement acceptables pour protéger vos Données à Caractère Personnel, nous ne pouvons pas leur garantir une sécurité absolue.</p>

        <h2>Droits à la protection des données qui vous sont accordés par le Règlement Général relatif à la Protection des Données (RGPD)</h2>
        <p>Si vous résidez dans l'Espace économique européen (EEE), vous avez certains droits en matière de protection des données. Lost Tracker entend prendre des mesures raisonnables pour vous permettre de corriger, de modifier, ou de supprimer vos Données à Caractère Personnel ou d'en limiter l'utilisation.</p>
        <p>Si vous souhaitez savoir quelles Données à Caractère Personnel nous détenons à votre sujet et voulez qu'elles soient supprimées de nos systèmes, veuillez nous contacter.</p>
        <p>Dans certaines circonstances, vous avez les droits suivants en matière de protection des données:</p>
        <ul>
            <li>
                <p><strong>Le droit d'accéder aux informations que nous détenons à votre sujet, de les actualiser ou de les supprimer.</strong> Lorsque cette option est proposée, vous pouvez consulter ou actualiser vos Données à Caractère Personnel ou en demander la suppression dans la section paramètres de votre compte. Si vous ne pouvez pas effectuer ces actions vous-même, merci de nous contacter pour obtenir de l'aide.</p>
            </li>
            <li>
                <p><strong>Droit de rectification.</strong> Vous avez le droit de faire rectifier vos données si elles sont inexactes ou incomplètes.</p>
            </li>
            <li>
                <p><strong>Droit d'opposition.</strong> Vous avez le droit de vous opposer à ce que nous traitions vos Données à Caractère Personnel.</p>
            </li>
            <li>
                <p><strong>Droit de limitation</strong> Vous avez le droit de nous demander de limiter le traitement de vos données personnelles.</p>
            </li>
            <li>
                <p><strong>Le droit à la portabilité des données.</strong> Vous avez le droit de recevoir une copie des informations que nous détenons à votre sujet dans un format couramment utilisé, structuré et lisible par une machine.</p>
            </li>
            <li>
                <p><strong>Droit au retrait du consentement.</strong> Vous avez également le droit de retirer votre consentement à tout moment si Lost Tracker s'est appuyé sur votre consentement pour traiter vos données personnelles.</p>
            </li>
        </ul>
        <p>Veuillez noter que nous pouvons vous demander de prouver votre identité avant de répondre à des demandes de cette nature.</p>

        <p>Vous avez le droit de déposer plainte auprès d'une autorité de protection des données au sujet de notre collecte et de notre utilisation de vos Données à Caractère Personnel. Pour plus de précisions, veuillez contacter l'autorité de protection des données la plus proche de vous dans l'Espace économique européen (EEE).</p>

        <h2>Prestataires de services</h2>
        <p>Nous pouvons faire appel à des sociétés tierces et à des tierces personnes pour faciliter la prestation de notre Service ("Prestataires de Services"), assurer le Service en notre nom, assurer des services liés au Service ou nous aider à analyser la façon dont notre Service est utilisé.</p>
        <p>Ces tiers n'ont accès à vos Données à Caractère Personnel que pour effectuer ces tâches en notre nom et il leur est interdit de les communiquer ou de les utiliser à quelle qu'autre fin. </p>

        <h2>Liens pointant vers d'autres sites</h2>
        <p>Il se peut que notre Service contienne des liens pointant vers d'autres sites que nous n'exploitons pas. Si vous cliquez sur un lien de tiers, vous serez redirigé vers le site de ce tiers. Nous vous recommandons vivement d'examiner la politique de confidentialité de chacun des sites que vous consultez.</p>
        <p>Nous n'avons aucun contrôle sur le contenu, les politiques ou pratiques de confidentialité des sites ou services de tiers et déclinons toute responsabilité en ce qui les concerne.</p>

        <h2>Vie privée des enfants</h2>
        <p>Notre Service ne s'adresse pas aux personnes de moins de 18 ans ("Enfants").</p>
        <p>Nous ne recueillons pas sciemment de données personnelles nominatives auprès de personnes de moins de 18 ans. Si vous êtes un parent ou un tuteur et que vous savez que votre Enfant nous a communiqué des Données à Caractère Personnel, veuillez nous contacter. Si nous apprenons que nous avons recueilli des Données à Caractère Personnel auprès d'enfants sans vérifier s'il y a consentement parental, nous faisons le nécessaire pour supprimer ces informations de nos serveurs.</p>

        <h2>Modifications de la présente Politique de Confidentialité</h2>
        <p>Nous nous réservons le droit d'actualiser notre Politique de Confidentialité de temps à autre. Nous vous informerons de toute modification en publiant la nouvelle Politique de Confidentialité sur cette page.</p>
        <p>Avant que la modification ne prenne effet, nous vous en informerons par e-mail et/ ou en plaçant un avis bien en vue dans notre Service et nous actualiserons la "date de prise d'effet" qui figure en haut de la présente Politique de Confidentialité.</p>
        <p>Nous vous conseillons de consulter la présente Politique de Confidentialité périodiquement pour prendre connaissance de toute modification. Les modifications apportées à la présente Politique de Confidentialité prennent effet lorsqu'elles sont publiées sur cette page.</p>

        <h2>Nous contacter</h2>
        <p>Pour toute question relative à la présente Politique de Confidentialité, veuillez nous contacter:</p>
        <ul>
            <li>Par courrier électronique: cheffen@lost.lu</li>
        </ul>
        </v-card-text>
    </v-card>
    </v-tab-item>
    <v-tab-item value="de">
    <v-card flat>
        <v-card-text class="text-xs-left">
        <h1>Datenschutz-Richtlinie</h1>

        <p>Datum des Inkrafttretens: May 09, 2019</p>

        <p>Lost Tracker ("wir", "uns", "unser" usw.) betreibt die Website https://tracker.lost.lu (nachstehend als "Dienst" bezeichnet).</p>

        <p>Diese Seite enthält Informationen zu der Art und Weise, auf welche wir personenbezogene Daten erfassen, nutzen und offenlegen, wenn Sie unseren Dienst nutzen, sowie zu den Optionen, die Ihnen im Zusammenhang mit diesen Daten zur Verfügung stehen.</p>

        <p>Wir nutzen Ihre Daten zur Bereitstellung und Verbesserung unseres Dienstes. Durch Inanspruchnahme des Dienstes erklären Sie sich mit der Erfassung und Nutzung von Daten durch uns nach Maßgabe dieser Richtlinie einverstanden. Soweit in dieser Datenschutz-Richtlinie nicht jeweils etwas anderes angegeben ist, kommt den in dieser Datenschutz-Richtlinie vorkommenden Begriffen jeweils dieselbe Bedeutung zu, die diesen in unseren Allgemeinen Geschäftsbedingungen (Terms and Conditions) (abrufbar über die  https://tracker.lost.lu) zugewiesen wurde.</p>

        <h2>Begriffsbestimmungen</h2>
        <ul>
            <li>
                <p><strong>Dienst</strong></p>
                        <p>Der Dienst ist die von dem Lost Tracker betriebene Website https://tracker.lost.lu</p>
                    </li>
            <li>
                <p><strong>Personenbezogene Daten</strong></p>
                <p>Personenbezogene Daten sind Daten, die sich auf eine lebende Person beziehen, welche anhand dieser Daten (bzw. anhand dieser Daten in Kombination mit weiteren Informationen, die sich bereits in unserem Besitz befinden oder mit Wahrscheinlichkeit in unseren Besitz gelangen werden) identifizierbar ist.</p>
            </li>
            <li>
                <p><strong>Nutzungsdaten</strong></p>
                <p>Nutzungsdaten sind Daten, die automatisch im Rahmen der Nutzung des Dienstes oder innerhalb der Dienstinfrastruktur selbst (beispielsweise für die Dauer eines Seitenbesuchs) erfasst werden.</p>
            </li>
            <li>
                <p><strong>Cookies</strong></p>
                <p>Cookies sind kleine Dateien, die auf Ihrem Gerät (Computer oder mobiles Endgerät) gespeichert werden.</p>
            </li>
                <li>
                <p><strong>Datenverantwortlicher</strong></p>
                <p>Der Datenverantwortliche ist eine natürliche oder juristische Person, die (entweder alleine oder zusammen mit weiteren Personen) die Zwecke sowie die Art und Weise festlegt, für bzw. auf welche personenbezogene Daten verarbeitet werden bzw. zu verarbeiten sind.</p>
                <p>Für die Zwecke dieser Datenschutz-Richtlinie sind wir der Datenverantwortliche in Bezug auf Ihre personenbezogenen Daten.</p>
            </li>
            <li>
                <p><strong>Datenverarbeiter (oder Leistungsanbieter)</strong></p>
                <p>Ein Datenverarbeiter (oder Leistungsanbieter) ist eine natürliche oder juristische Person, welche die Daten im Namen des Datenverantwortlichen verarbeitet.</p>
                <p>Wir können die Leistungen verschiedener Leistungsanbieter in Anspruch nehmen, um Ihre Daten auf effizientere Weise zu verarbeiten.</p>
            </li>
            <li>
                <p><strong>Datensubjekt (oder Nutzer)</strong></p>
                <p>Ein Datensubjekt ist eine lebende Einzelperson, die unseren Dienst in Anspruch nimmt und Gegenstand personenbezogener Daten ist.</p>
            </li>
            </ul>

        <h2>Erfassung und Nutzung von Daten</h2>
        <p>Wir erfassen verschiedene Arten von Daten für eine Reihe von Zwecken, um den Dienst, den wir Ihnen zur Verfügung stellen, zu verbessern.</p>

        <h3>Arten der erfassten Daten</h3>

        <h4>Personenbezogene Daten</h4>
        <p>Im Rahmen der Nutzung unseres Dienstes bitten wir Sie gegebenenfalls um die Zurverfügungstellung bestimmter persönlich identifizierbarer Daten, die wir dazu nutzen, um Sie zu kontaktieren oder zu identifizieren ("personenbezogene Daten"). Persönlich identifizierbare Daten umfassen beispielsweise folgende Daten (sind jedoch nicht auf diese beschränkt):</p>

        <ul>
            <li>E-Mail-Adresse</li>        <li>Telefonnummer</li>        <li>Cookies und Nutzungsdaten</li>
        </ul>

        <h4>Nutzungsdaten</h4>

        <p>Wir können außerdem Daten zu der Art und Weise erfassen, auf welche auf unseren Dienst zugegriffen wird bzw. auf welche diese genutzt werden ("Nutzungsdaten"). Diese Nutzungsdaten umfassen gegebenenfalls die Internet-Protocol-Adresse (IP-Adresse) Ihres Computers, Ihren Browsertyp, Ihre Browserversion, die von Ihnen innerhalb unseres Dienstes besuchten Seiten, den Zeitpunkt und das Datum Ihres Besuchs, die Gesamtverweildauer auf den betreffenden Seiten, individuelle Geräteidentifikationsmerkmale und weitere Diagnostikdaten.</p>

        <h4>Tracking & Cookies</h4>
        <p>Wir setzen Cookies und ähnliche Tracking-Technologien zur Überwachung der Aktivität innerhalb unseres Dienstes ein und speichern in diesem Zusammenhang bestimmte Daten.</p>
        <p>Cookies sind Dateien mit einem geringen Datenumfang, wie zum Beispiel anonyme einzigartige Identifikatoren. Cookies werden von einer Website an Ihren Browser gesendet und auf Ihrem Gerät gespeichert. Die sonstigen von uns eingesetzten Tracking-Technologien sind so genannte Beacons, Tags und Scripts und dienen der Erfassung und Nachverfolgung von Daten sowie der Verbesserung und Analyse unseres Dienstes.</p>
        <p>Sie können in den Einstellungen Ihres Browsers bestimmen, ob Sie alle Cookies ablehnen oder nur bestimmte Cookies akzeptieren möchten. Falls Sie jedoch die Annahme von Cookies verweigern, können Sie gegebenenfalls Teile unseres Dienstes nicht in Anspruch nehmen.</p>
        <p>Beispiele für von uns eingesetzte Cookies:</p>
        <ul>
            <li><strong>Sitzungs-Cookies.</strong> Wir setzen Sitzungs-Cookies für den Betrieb unseres Dienstes ein.</li>
            <li><strong>Präferenz-Cookies.</strong> Wir setzen Präferenz-Cookies ein, um Ihre Präferenzen und verschiedenen Einstellungen zu speichern.</li>
            <li><strong>Sicherheits-Cookies.</strong> Wir setzen Sicherheits-Cookies für Sicherheitszwecke ein.</li>
            </ul>

        <h2>Datennutzung</h2>
        <p>Wir bei Lost Tracker nutzen die erfassten Daten für verschiedene Zwecke, beispielsweise um:</p>
        <ul>
            <li>Ihnen unseren Dienst zur Verfügung zu stellen und diesen aufrecht zu erhalten;</li>
            <li>Ihnen Änderungen in Bezug auf unseren Dienst mitzuteilen;</li>
            <li>es Ihnen auf Wunsch zu ermöglichen, an den interaktiven Teilen unseres Dienstes teilzunehmen;</li>
            <li>Kundendienstleistungen zur Verfügung zu stellen;</li>
            <li>Analysedaten und sonstige wertvolle Daten zu erfassen, damit wir unseren Dienst verbessern können;</li>
            <li>die Nutzung unseres Dienstes zu überwachen;</li>
            <li>technische Probleme zu erkennen, zu vermeiden und zu beheben;</li>
            </ul>

        <h2>Rechtliche Grundlage für die Verarbeitung personenbezogener Daten nach Maßgabe der Datenschutz-Grundverordnung (DSGVO)</h2>
        <p>Falls sich Ihr Wohnsitz innerhalb des Europäischen Wirtschaftsraums (EWR) befindet, hängt die rechtliche Grundlage von Lost Tracker für die Erfassung und Nutzung der in dieser Datenschutz-Richtlinie beschriebenen personenbezogenen Daten von den von uns erfassten personenbezogenen Daten sowie von dem erfassungsspezifischen Kontext ab.</p>
        <p>Wir bei Lost Tracker können Ihre personenbezogenen Daten aus folgenden Gründen verarbeiten:</p>
        <ul>
            <li>Wir müssen einen mit Ihnen eingegangen Vertrag erfüllen.</li>
            <li>Sie haben uns hierzu Ihre Zustimmung erteilt.</li>
            <li>Die Verarbeitung dient unseren legitimen Interessen, und diese sind Ihren Rechten gegenüber nicht nachrangig.</li>
                <li>Die Verarbeitung dient der Einhaltung der gesetzlichen Bestimmungen.</li>
        </ul>

        <h2>Aufbewahrung von Daten</h2>
        <p>Lost Tracker wird Ihre personenbezogenen Daten nur so lange aufbewahren, wie dies für die Zwecke dieser Datenschutz-Richtlinie erforderlich ist. Wir werden Ihre personenbezogenen Daten in dem Umfang aufbewahren und nutzen, wie es für die Erfüllung unserer gesetzlichen Pflichten (falls wir Ihre Daten beispielsweise zur Einhaltung anwendbarer Gesetze aufbewahren müssen), zur Beilegung von Streitigkeiten sowie zur Durchsetzung unserer rechtlichen Vereinbarungen und Richtlinien erforderlich ist.</p>
        <p>Lost Tracker wird außerdem Nutzungsdaten für interne Analysezwecke aufbewahren. Nutzungsdaten werden üblicherweise für kürzere Zeiträume aufbewahrt, soweit diese nicht für eine Verstärkung unserer Sicherheitsvorkehrungen oder eine Verbesserung der Funktionalität unseres Dienstes eingesetzt werden oder wir nicht gesetzlich zu einer längeren Aufbewahrung verpflichtet sind.</p>

        <h2>Übertragung von Daten</h2>
        <p>Ihre Daten, einschließlich personenbezogener Daten, können auf Computer übertragen – und auf solchen aufbewahrt – werden, die sich außerhalb Ihres Heimatstaates, Ihrer Heimatprovinz, Ihres Heimatlandes oder einer sonstigen Rechtsordnung befinden und somit Datenschutzgesetzen unterliegen, die sich von den Datenschutzgesetzen in Ihrer Rechtsordnung unterscheiden.</p>
        <p>Falls Sie sich außerhalb von Luxembourg befinden und sich dazu entscheiden, Daten an uns zu übermitteln, müssen Sie zur Kenntnis nehmen, dass wir Ihre Daten, einschließlich personenbezogener Daten, nach Luxembourg übertragen und diese dort verarbeiten.</p>
        <p>Ihre Zustimmung zu dieser Datenschutz-Richtlinie und eine nachfolgende Übermittlung von Daten Ihrerseits stellt eine Einverständniserklärung Ihrerseits zu der genannten Übertragung dar.</p>
        <p>Lost Tracker wird alle im zumutbaren Rahmen erforderlichen Schritte unternehmen um sicherzustellen, dass Ihre Daten auf sichere Weise sowie in Übereinstimmung mit dieser Datenschutz-Richtlinie behandelt werden, und dass Ihre personenbezogenen Daten nicht an Organisationen oder in Länder übertragen werden, hinsichtlich welcher keine hinreichenden Kontrollmechanismen in Bezug auf die Sicherheit Ihrer Daten und sonstigen personenbezogenen Informationen vorliegen.</p>

        <h2>Offenlegung von Daten</h2>

        <h3>Gesetzliche Anforderungen</h3>
        <p>Lost Tracker kann Ihre personenbezogenen Daten unter Umständen offenlegen, wenn es unter Beachtung der Grundsätze von Treu und Glauben der Ansicht ist, dass dies zur Erreichung der nachfolgenden Zielsetzungen erforderlich ist:</p>
        <ul>
            <li>zur Erfüllung einer gesetzlichen Pflicht</li>
            <li>zum Schutz und zur Verteidigung der Rechte oder des Eigentums von Lost Tracker</li>
            <li>zur Vermeidung oder Untersuchung möglicher Fehlverhaltensweisen in Bezug auf den Dienst </li>
            <li>zum Schutz der persönlichen Sicherheit der Nutzer des Dienstes oder der Öffentlichkeit</li>
            <li>zur Vermeidung von Haftungsansprüchen</li>
        </ul>

        <h2>Datensicherheit</h2>
        <p>Die Sicherheit Ihrer Daten ist uns wichtig. Bitte vergessen Sie jedoch nicht, dass es keine Übertragungsmethoden über das Internet und keine elektronischen Speichermedien gibt, die 100 % sicher sind. Obwohl wir stets bemüht sind, kommerziell annehmbare Maßnahmen zum Schutz Ihrer personenbezogenen Daten umzusetzen, können wir eine absolute Sicherheit nicht garantieren.</p>

        <h2>Ihre Datenschutzrechte im Rahmen der Datenschutz-Grundverordnung (DSGVO)</h2>
        <p>Soweit sich Ihr Wohnsitz innerhalb des Europäischen Wirtschaftsraums (EWR) befindet, haben Sie bestimmte Datenschutzrechte. Lost Tracker ist bestrebt, zumutbare Maßnahmen umzusetzen, die es Ihnen erlauben, Ihre personenbezogenen Daten zu korrigieren, zu ändern, zu löschen oder deren Nutzung zu beschränken.</p>
        <p>Falls Sie in Erfahrung bringen möchten, welche personenbezogenen Daten wir zu Ihnen gespeichert haben, und falls Sie eine Löschung Ihrer Daten aus unserem System wünschen, nehmen Sie bitte Kontakt zu uns auf.</p>
        <p>Unter bestimmten Umständen haben Sie die folgenden Datenschutzrechte:</p>
        <ul>
            <li>
                <p><strong>Das Recht auf Zugriff auf die Daten, die wir zu Ihnen gespeichert haben, sowie auf deren Aktualisierung bzw.</strong> Löschung. Soweit dies jeweils möglich ist, können Sie auf Ihre personenbezogenen Daten direkt in dem Abschnitt mit Ihren Account-Einstellungen zugreifen sowie diese aktualisieren bzw. um deren Löschung bitten. Falls es Ihnen nicht möglich ist, diese Handlungen selbst vorzunehmen, nehmen Sie bitte Kontakt zu uns auf, damit wir Ihnen behilflich sein können.</p>
            </li>
            <li>
                <p><strong>Das Recht auf Berichtigung.</strong> Sie haben das Recht auf Berichtigung Ihrer Daten, falls diese unzutreffend oder unvollständig sein sollten.</p>
            </li>
            <li>
                <p><strong>Das Recht auf Widerspruch.</strong> Sie haben das Recht, einer Verarbeitung Ihrer personenbezogenen Daten durch uns zu widersprechen.</p>
            </li>
            <li>
                <p><strong>Das Recht auf Beschränkung.</strong> Sie haben das Recht, die Verarbeitung Ihrer personenbezogenen Daten durch uns zu beschränken.</p>
            </li>
            <li>
                <p><strong>Das Recht auf Datenportabilität.</strong> Sie haben das Recht, von uns die Aushändigung einer Abschrift der Daten, die wir zu Ihnen gespeichert haben, in einem strukturierten, maschinenlesbaren und üblichen Format zu verlangen.</p>
            </li>
            <li>
                <p><strong>Das Recht auf Zustimmungsrücknahme.</strong> Sie haben außerdem das Recht, Ihre Zustimmung in Fällen, in denen Lost Tracker rsich auf Ihre Zustimmung zur Verarbeitung Ihrer personenbezogenen Daten verlassen hat, jederzeit zurückzunehmen.</p>
            </li>
        </ul>
        <p>Bitte nehmen Sie zur Kenntnis, dass wir vor einer Bearbeitung solcher Anfragen gegebenenfalls Ihre Identität überprüfen.</p>

        <p>Sie haben das Recht, in Bezug auf die Erfassung und Nutzung Ihrer personenbezogenen Daten eine Beschwerde bei einer Datenschutzbehörde einzulegen. Nähere Informationen in diesem Zusammenhang können Sie von der für Sie örtlich zuständigen Datenschutzbehörde innerhalb des Europäischen Wirtschaftsraums (EWR) erfragen.</p>

        <h2>Leistungsanbieter</h2>
        <p>Wir beauftragen gegebenenfalls dritte Unternehmen und Einzelpersonen ("Leistungsanbieter") mit Unterstützungsleistungen zum einfacheren Angebot unseres Dienstes, mit der Erbringung von Leistungen in unserem Namen, mit der Erbringung von mit unserem Dienst verbundenen Leistungen oder mit Unterstützungsleistungen zur Analyse der Art und Weise, auf die unser Dienst in Anspruch genommen wird.</p>
        <p>Diese Dritten können auf Ihre personenbezogenen Daten nur in dem Umfang Zugriff nehmen, der für die Erfüllung der genannten Aufgaben in unserem Namen erforderlich ist, und dürfen diese für keine sonstigen Zwecke offenlegen oder nutzen.</p>

        <h2>Links zu anderen Websites</h2>
        <p>Unser Dienst kann Links zu anderen Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen Drittlink klicken, werden Sie direkt auf die Website des betreffenden Dritten weitergeleitet. Wir empfehlen Ihnen dringend, sich jeweils die Datenschutz-Richtlinien aller von Ihnen besuchten Websites durchzulesen.</p>
        <p>Wir haben keine Kontrolle über die Inhalte, Datenschutzvorschriften und -praktiken dritter Websites oder Dienste und übernehmen in diesem Zusammenhang keine Haftung.</p>

        <h2>Privatsphäre Minderjähriger</h2>
        <p>Unser Dienst richtet sich nicht an Personen, die das 18. Lebensjahr noch nicht vollendet haben ("minderjährige Personen").</p>
        <p>Wir erfassen wissentlich keine persönlich identifizierbaren Daten zu minderjährigen Personen. Falls Sie ein Elternteil oder Vormund sind und es Ihnen bekannt wird, dass eine Ihrer Aufsicht unterstehende minderjährige Person uns personenbezogene Daten übermittelt hat, bitten wir Sie, mit uns Kontakt aufzunehmen. Falls uns bekannt wird, dass wir personenbezogene Daten einer minderjährigen Person ohne elterliche Zustimmung erfasst haben, setzen wir Maßnahmen zur Entfernung dieser Daten von unseren Servern um.</p>

        <h2>Änderungen dieser Datenschutz-Richtlinie</h2>
        <p>Wir können unsere Datenschutz-Richtlinie von Zeit zu Zeit aktualisieren. Jegliche solcher Änderungen teilen wir Ihnen mit, indem wir die aktualisierte Fassung auf dieser Seite veröffentlichen.</p>
        <p>Wir werden Sie vor dem Inkrafttreten der betreffenden Änderung per E-Mail und/oder mittels einer sonstigen sichtbaren Mitteilung innerhalb unseres Dienstes informieren und das "Datum des Inkrafttretens" am Beginn dieser Datenschutz-Richtlinie aktualisieren.</p>
        <p>Wir empfehlen Ihnen, diese Datenschutz-Richtlinie regelmäßig auf Änderungen hin durchzusehen. Änderungen dieser Datenschutz-Richtlinie werden im Zeitpunkt ihrer Veröffentlichung auf dieser Seite wirksam.</p>

        <h2>Kontaktaufnahme</h2>
        <p>Falls Sie Fragen zu dieser Datenschutz-Richtlinie haben, können Sie wie folgt Kontakt zu uns aufnehmen:</p>
        <ul>
                <li>Per E-Mail: cheffen@lost.lu</li>
                </ul>
        </v-card-text>
    </v-card>
    </v-tab-item>
  </v-tabs>
</template>

<style scoped>
LI {
  margin-left: 2em;
}
</style>

<script>
export default {
  data () {
    return {
      selectedLanguage: null
    }
  }
}
</script>
