---
name: Build and Publish
on:
  workflow_dispatch:
  push:
    tags: ['v*']
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add dependencies
        run: sudo apt-get install -y jq
      - name: Get Version
        run: echo "PROJECT_VERSION=$(jq -r .version package.json)"
          >> "${GITHUB_ENV}"
      - name: Add secrets to .env file
        run: echo "VITE_PUSHER_KEY=${{secrets.VITE_PUSHER_KEY}}"
          >> .env.local
      - name: Build Image
        # env-vars need to be "pushed" through to the build-context
        run: "
          docker build
          -t \"${{secrets.DOCKER_REGISTRY}}/\
          powonline-frontend:${PROJECT_VERSION}\"
          --build-arg=\"VITE_BACKEND_URL=${{vars.VITE_BACKEND_URL}}\"
          --build-arg=\"VITE_FACEBOOK_PUBLIC_KEY=\
          ${{secrets.VITE_FACEBOOK_PUBLIC_KEY}}\"
          --build-arg=\"VITE_GOOGLE_PUBLIC_KEY=\
          ${{secrets.VITE_GOOGLE_PUBLIC_KEY}}\"
          --build-arg=\"VITE_NODE_ENV=${{vars.VITE_NODE_ENV}}\"
          --build-arg=\"VITE_PAGE_TITLE=${{vars.VITE_PAGE_TITLE}}\"
          --build-arg=\"VITE_PUSHER_DEBUG=${{vars.VITE_PUSHER_DEBUG}}\"
          --build-arg=\"VITE_PUSHER_FILE_CHANNEL=\
          ${{vars.VITE_PUSHER_FILE_CHANNEL}}\"
          --build-arg=\"VITE_PUSHER_KEY=${{secrets.VITE_PUSHER_KEY}}\"
          --build-arg=\"VITE_PUSHER_TEAM_CHANNEL=\
          ${{vars.VITE_PUSHER_TEAM_CHANNEL}}\"
          ."
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push
        run: "docker push \"${{secrets.DOCKER_REGISTRY}}/\
          powonline-frontend:${PROJECT_VERSION}\""
